# Generated by Django 5.1.5 on 2025-02-13 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, help_text='Загрузите изображение рецепта (необязательно)', null=True, upload_to='recipes/'),
        ),
    ]
